
import "./globals.css";
import AuthProvider from "./AuthProvider"
export const metadata = {
  title: "FamilyHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body > 

      <AuthProvider/>

      <div className="flex flex-col bg-white ">



        <div className="flex">


          <div className="w-full ">
            {children}
          </div>
          </div>

        </div>
        </body>
    </html>
  );
}
