
import { Inter } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "FamilyHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body > 
        <div className="flex  bg-gray-300">    

          <div className="w-full ">
            {children}
          </div>

        </div>
        </body>
    </html>
  );
}
