
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header"
import Sidebar from "./components/Sidebar/Sidebar"
import Dashboard from "./components/Dashboard"

export const metadata = {
  title: "FamilyHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body > 
      <div className="flex flex-col bg-white ">
      <Dashboard />

        <Header/>
        <div className="flex">

        <Sidebar/>

          <div className="w-full ">
            {children}
          </div>
          </div>

        </div>
        </body>
    </html>
  );
}
